---
kind: pipeline
type: docker
name: test

trigger:
  branch:
    exclude:
      - master

steps:
  - name: Build&Push Docker Image to Registry
    image: plugins/docker
    secrets:
      - source: home_registry_host
        target: home_registry_host
    settings:
      registry: 
        from_secret: home_registry_host
      repo: ${HOME_REGISTRY_HOST}/adam/${DRONE_REPO_NAME}
      username: 
        from_secret: home_registry_username
      password: 
        from_secret: home_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - v*.*

  # TODO: Include some automated testing here

  - name: notify_developer
    image: plugins/webhook
    settings:
      urls:
        from_secret: gotify_endpoint
      content_type: application/json
      template: |
        {
          "priority": 5,
          "title": "Drone DevOps",
          "message": "[${DRONE_BUILD_STATUS}] ${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH} image has been built and pushed to home registry! Test has been completed on it."
        }
    depends_on:
      - Build&Push Docker Image to Registry
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: production

trigger:
  branch:
    - master

steps:
  - name: Build&Push Docker Image to Registry
    image: plugins/docker
    settings:
      registry: docker.io
      repo: docker.io/atomicbeast101/${DRONE_REPO_NAME}
      username: 
        from_secret: remote_registry_username
      password: 
        from_secret: remote_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      branch:
        - master

  - name: notify_developer
    image: plugins/webhook
    settings:
      urls:
        from_secret: gotify_endpoint
      content_type: application/json
      template: |
        {
          "priority": 5,
          "title": "Drone DevOps",
          "message": "[${DRONE_BUILD_STATUS}] ${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH} image has been built and pushed to docker.io!"
        }
    depends_on:
      - Build&Push Docker Image to Registry
    when:
      status: [success, failure]
