global-variables:
  home_repo: adam/${DRONE_REPO_NAME}
  remote_repo: atomicbeast101/${DRONE_REPO_NAME}

# Test
---
kind: pipeline
type: docker
name: test

trigger:
  branch: 
    - v*.*
    - master

steps:
  - name: Build&Push Docker Image to Home Registry
    image: plugins/docker
    settings:
      registry: 
        from_secret: home_registry_host
      repo: *home_repo
      username: 
        from_secret: home_registry_username
      password: 
        from_secret: home_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - v*.*
        - master

  # TODO: Include some automated testing here

  - name: Build&Push Docker Image to Remote Registry
    image: plugins/docker
    settings:
      registry: docker.io
      repo: *remote_repo
      username: 
        from_secret: remote_registry_username
      password: 
        from_secret: remote_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      branch:
        - master

  - name: notify_developer
    image: fredix/arm64v8-alpine-drone-gotify
    settings:
      gotifyendpoint: 
        from_secret: gotify_endpoint
      gotifytoken: 
        from_secret: gotify_token
      gotifytitle: 
      gotifypriority: 5
      message: >
        {{#success build.status}}
          ${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH} image has been built and successfully tested!
        {{else}}
          Tests has failed for ${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH}! Please see logs for details.
        {{/success}}
    depends_on:
      - Build&Push Docker Image to Home Registry
      - Build&Push Docker Image to Remote Registry
    when:
      status: [success, failure]
