# Test
---
kind: pipeline
type: docker
name: default

trigger:
  branch: 
    - v*.*

steps:
  - name: build_docker_image
    image: plugins/docker
    settings:
      registry: 
        from_secret: test_registry_host
      repo: 
        from_secret: test_registry_repo
      username: 
        from_secret: test_registry_username
      password: 
        from_secret: test_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}

# Production
---
kind: pipeline
type: docker
name: default

trigger:
  branch: 
    - master

steps:
  - name: build_docker_image
    image: plugins/docker
    settings:
      registry: docker.io
      repo: docker.io/atomicbeast101/ha-projector-controller-server
      username: 
        from_secret: prod_registry_username
      password: 
        from_secret: prod_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
        - latest
