---
kind: pipeline
type: docker
name: test

steps:
  - name: Build&Push Docker Image to Home Registry
    image: plugins/docker
    settings:
      registry: 
        from_secret: home_registry_host
      repo: registry.potatolab.dev/adam/${DRONE_REPO_NAME}
      username: 
        from_secret: home_registry_username
      password: 
        from_secret: home_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
    when:
      branch:
        - v*.*
        - master

  # TODO: Include some automated testing here

  - name: Build&Push Docker Image to Remote Registry
    image: plugins/docker
    settings:
      registry: docker.io
      repo: docker.io/atomicbeast101/${DRONE_REPO_NAME}
      username: 
        from_secret: remote_registry_username
      password: 
        from_secret: remote_registry_password
      tags: 
        - ${DRONE_COMMIT_BRANCH}
        - latest
    when:
      branch:
        - master

  - name: notify_developer
    image: plugins/webhook
    settings:
      urls:
        from_secret: gotify_endpoint
      content_type: application/json
      template: |
        {
          "priority": 5,
          "title": "Drone DevOps",
          "message": "${DRONE_BUILD_STATUS} on building & testing ${DRONE_REPO_NAME}:${DRONE_COMMIT_BRANCH} image!"
        }
    depends_on:
      - Build&Push Docker Image to Home Registry
      - Build&Push Docker Image to Remote Registry
    when:
      status: [success, failure]
